### ISSUE TITLE
Failed to unmap `<Enter>' in normal mode

### ISSUE THREAD

**Issue by cp00-home** [zphixon/vis-netrw#1]
I get this message when trying to open the netrw browser. When I hit Enter i get ../vis-netrw.lua:40: attempt to index a nil value (field 'cursor'). Is this caused by netrw or is there some other issue with my current plugins?

**Comment by zphixon** [comment]
The API changed at some point within the last three years, it looks like `vis.win.cursor` no longer exists. I don't have any interest in maintaining this plugin since I don't use vis anymore but if you manage to come up with something do submit a pull request :)

API doc: http://martanne.github.io/vis/doc/
